# Ensure local contributors run the same Rust quality gates as CI.
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt --all
        entry: cargo
        args: ["fmt", "--all"]
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy --all-targets -- -D warnings
        entry: cargo
        args: ["clippy", "--all-targets", "--", "-D", "warnings"]
        language: system
        pass_filenames: false
